# This file was auto-generated by cabal2nix4dev. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
let
  inherit (haskellPackages)
    cabal aeson byteable cryptohash lens shakespeare text time
    transformers yesod yesodCore yesodForm
    ;

in cabal.mkDerivation (self: {
  pname = "transloadit-yesod";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    aeson byteable cryptohash lens shakespeare text time transformers
    yesod yesodCore yesodForm
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
