# This file was auto-generated by cabal2nix4dev. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:

let
  pkgs = import <nixpkgs> {};
  hspkgs = haskellPackages.override {
    extension = self: super: {
      transloadit-yesod = self.callPackage ./. {
        haskellPackages = hspkgs;
      };
    };
  };

in pkgs.lib.overrideDerivation hspkgs.transloadit-yesod (attrs: {
     buildInputs = [ hspkgs.cabalInstall ] ++ attrs.buildInputs;
   })
